### ISSUE TITLE
Potential visual sprite bug from Merge 28/08(August)/2024

### ISSUE THREAD

**Issue by WithinAmnesia** [SlayHorizon/godot-tiny-mmo-demo#21]
https://github.com/SlayHorizon/godot-tiny-mmo-demo/commit/6739c4fd06fa51254b29028a18989ff5e7a833ce
![M M O A R P G (V 000 019) Godot-Tiny-MMO-Demo-0 0 7 Godot 4 3 NET+ Godot Tiny MMO (0) Bugged](https://github.com/user-attachments/assets/09768292-bb82-4102-ae37-397f586b1ff8)
The Warrior / knight sprite is invisible after the latest merge on this test build. Is this a local issue on my end or a potential build issue? The previous 3rd dungeon area lower left gate wall overlap bug is fixed though so that's good.

**Comment by d-Cadrius** [comment]
Hi Amnesia,
I currently do not have said issue on my side with the latest merge but you may want to check out the following resource:
/common/resources/builtin/sprite_frames_collection/knight.tres
The knight animation file may be missing and or corrupted or you can always check the login menu itself to see if the sprite has its sprite frame attached to it:
![image](https://github.com/user-attachments/assets/5459ed41-bde5-40e3-b157-2540699626a2)
![image](https://github.com/user-attachments/assets/ea5d88be-eb18-4caa-99a0-eaa29f63eead)

**Comment by WithinAmnesia** [comment]
First thoughts to double check. May you @d-Cadrius clone the repo and see if its a repo issue too? Either way its an easy fix.

**Comment by WithinAmnesia** [comment]
"The knight animation file may be missing and or corrupted..."
![image](https://github.com/user-attachments/assets/f476d7f2-8676-4513-b383-3db054fe95d5)
![image](https://github.com/user-attachments/assets/9ca51bae-561b-42af-bdb7-a155e555ef01)
![image](https://github.com/user-attachments/assets/efe3599f-622e-45f6-83d1-af0da9cacf61)
Ah-ha lol its the knight file corrupted; I think. I'll re-clone the latest repo and triple check if its a corrupted file.

**Comment by WithinAmnesia** [comment]
![M M O A R P G (V 000 020) Godot-Tiny-MMO-Demo-0 0 8 Godot 4 3 NET+ Godot Tiny MMO (0) Working](https://github.com/user-attachments/assets/f8a63cf4-a1e7-42cb-9f46-3641a176e4a0)
I recloned the latest repo and it works. Lets hope it was on my end and a local copy and paste issue and not a repo issue. This looks good and I think this is stable so far.

**Comment by WithinAmnesia** [comment]
I think this issue is solved.
