### ISSUE TITLE
Possible testing issues. Looks good too!

### ISSUE THREAD

**Issue by WithinAmnesia** [SlayHorizon/godot-tiny-mmo-demo#29]
I noticed the first 'run' / re-loading of assets had a memory crash (a first time for this project) and there was not another ~'memory cannot be read' crash after the second re-import of assets when running the project.

Also I'm not sure how the 'press alt feature' is supposed to show visuals but I like the idea. I've tried with pressing left and or right alt on my windows machine and it does not register or there something else to also test? I'm not sure what the working visuals should look like but from the commit description it says it draws an info box around the current mouse position? Maybe my keybinds are not set up or I wonder what it could be; any suggestions?

Also I'm wondering what the 1 and 2 buttons / icons on the right side of the HUD / GUI are?

Also here is a screenshot of the current build test. It looks great! Keep up the great work and its coming together really good so far!
![M M O A R P G (V 000 063) Godot-Tiny-MMO-Demo-0 0 23 Godot 4 3 NET+ Godot Tiny MMO (1)](https://github.com/user-attachments/assets/06bc8ab5-9b6d-40fc-8ade-26a3abd1a58f)
💪 😃 👍 ✨ 💯 🚀

**Comment by SlayHorizon** [comment]
This issue should be solved on the next version of Godot that's why we'll move to it this week.

Buttons on the right are shortcuts to equip item faster:
https://github.com/user-attachments/assets/b8880ec7-cd0c-448a-b882-4702700baf4b

**Comment by WithinAmnesia** [comment]
> This issue should be solved on the next version of Godot that's why we'll move to it this week.
> 
> Buttons on the right are shortcuts to equip item faster: https://github.com/user-attachments/assets/b8880ec7-cd0c-448a-b882-4702700baf4b

It's good to hear the engine version upgrade in the near future is to help the build; that's really neat. That's really good! The number buttons are like weapon sets to swap to which is super cool. That's really good to see so much progress, keep it up and its looking really good! 💪 😃 👍 ✨ 🚀 💯

**Comment by WithinAmnesia** [comment]
![M M O A R P G (V 000 064) Godot-Tiny-MMO-Demo-0 0 24 Godot 4 3 NET+ Godot Tiny MMO (0)](https://github.com/user-attachments/assets/6e109c51-7a55-4b51-8ed1-609041b6b580)
It looks really good so far! I'm not sure how to equip / swap to the weapons even when pressing the 1 and 2 buttons and clicking them. It is really cool and great job so far.

I suppose in the near future that should be working and it just needs bit by bit and keep working away and focusing and bit by bit, start after start the project will get very much better and better! Whats the future plans so far?

Do you need any GUI or art or something I can help in that is CC0 / MIT that could be really handy for the time being? Need any help with anything or have any questions feel free to ask; all feedback is welcome. 💪 😄 👍 💯 ✨ 🚀

**Comment by WithinAmnesia** [comment]
I've not seen this run crash issue recently in the most recent versions of Tiny MMO Demo. I think this is working currently. Good job too!
