### ISSUE TITLE
Characters should be infinite in number (bug with only 1 character type per account logged in)[3 characters max per server]

### ISSUE THREAD

**Issue by WithinAmnesia** [SlayHorizon/godot-tiny-mmo-demo#32]
![M M O A R P G (V 000 077) Godot-Tiny-MMO-Demo-0 0 30 Godot 4 3 NET+ Godot Tiny MMO (Account Login Time!)(0)](https://github.com/user-attachments/assets/3c044951-8b8f-424b-9fcb-c73b8045bde9)
There can only be 3 characters logged in at one time (one Warrior, one Rogue, one Wizard) and this should be where it is ~infinite amounts of Warriors, Rogues and Wizards with ~infinite amount of accounts. So a server can have more than 3 player max per time oops lol but its really good so far.

It might be tied to the cool guest account where it has placeholder login and password and the server might be like seeing the same login / password / account name and trying its best to not have 2 characters on screen with the same account info to run properly. I could be wrong but its worth a little peak under the hood for.

This is super cool and thanks for making the login screen its really cool! I'm really excited about login features and account creation and account data storage like it is so close its amazing! Really good job too super cool!
😃 👍 ✨ 🗺️ 🏰 💯

**Comment by SlayHorizon** [comment]
The gateway system is still in experimental state as mentioned in the last commit message, I'll work on making it more stable but it looks like your error likely come from the expiration timer, it's supposed to happen when you stay too long on the gateway (15 minutes). Anyway I tried to replicate the issue on my side and as you see below it's working well.
![image](https://github.com/user-attachments/assets/8c13bb71-ec0c-4cdb-b464-0ce3409e66dc)

**Comment by SlayHorizon** [comment]
0d15dcf66603519d98f777e3377086c43bbb8612 should solve the timer issue.

**Comment by WithinAmnesia** [comment]
Thank you very much and it's looking really good, great job! 👍 😃 ✨

**Comment by WithinAmnesia** [comment]
![M M O A R P G (V 000 080) Godot-Tiny-MMO-Demo-0 0 31 Godot 4 3 NET+ Godot Tiny MMO (Infinite Players Login!)(0)](https://github.com/user-attachments/assets/41620fff-8458-47de-8a49-fd89064df6f6)
It works great! Keep up the good work, its really awesome. Thank you for the working login and account system its really cool to see it in action. It's a really big success! 😃 👍 💯 ✨ 🥇 ⛰️ 🏰 ⚔️ 🗺️
