### ISSUE TITLE
Unable to load / import load asset loop errors.

### ISSUE THREAD

**Issue by WithinAmnesia** [SlayHorizon/godot-tiny-mmo-demo#34]
The latest build has this problem. This might be a 4.3 thing I'm not sure but this has happened with other projects before.
Here are the error behavior screenshots in order when trying to play the demo:
<details>

![image](https://github.com/user-attachments/assets/56a2eb2f-89de-4a0e-87b6-1e8c0c7e7878)
![image](https://github.com/user-attachments/assets/876f02ed-4d15-4c46-a75e-09f27b796a0f)
![image](https://github.com/user-attachments/assets/945fe544-003d-4520-b2ec-92cac0a01ef5)
![image](https://github.com/user-attachments/assets/016bbc34-29a5-43ff-9760-5cc22c823bec)
![image](https://github.com/user-attachments/assets/4f4e71b6-e6d6-4335-9278-af5ead7cfdfb)
This is the run instances setup:
![image](https://github.com/user-attachments/assets/864f959a-6f62-44f8-8d43-e295c3ae01b2)

</details>
It runs, has import errors then boots up the login screen, then it says that it cannot connect, then the load error popup shows up and it repeats in a cycle of error load import error popups until stopped. I tried to delete the Github file on the first attempt after running it for a start. Then I tried a straight from zip file unzip fresh demo project directory thinking maybe it was a directory path or copy paste issue but same errors again.

Then I tried closing Godot completely and restarting and then trying the previous steps again on a restarted Godot it was the same import error messages. Then after trying all that I tried running a fresh unzipped directory and deleting the Godot file after 1 run and its still the same import error looping issues.

I'm not sure what the issue is but it is common in other projects and I think its a known Godot issue with at least version 4.3. This might be patched out in 4.4 but that's from a not 100% clear memory of reading the patch notes for Godot 4.4 in that this might have been patched out or fixed or it was a known issue type of thing.

I've personally encountered this same issue a few times across a few Godot projects from github. Also I've done this type of load error loops myself on saving a project then zipping it. Then when unzipping I encountered the same type of load errors from I think with something like odd saved variables or settings and then the imported version after being zipped was all crazy with import error loops after the zip.

Yet the original project was fine when running. Yet the load errors only showed up in zipping the original project then unzipping a copied project after unzipping and running to make the load errors appear. I am not 100% sure what the error cause is but I figured to tell you in case it was like me where my project ran great on my pc on the original project but it had crazy import errors with the copied project after zip due to like Godot file or import or github ignore or something like that not liking the zip, copy, paste, unzip and run process of testing.

The other patches ran super great its just the new one is all. It looks really good and I look forward to playing it. This is awesome and great job on this so far. It's super cool. 😃 👍 💯

**Comment by SlayHorizon** [comment]
This issue is fairly common on Windows, and one possible fix is to run Godot as an administrator. The import errors could also be related to permission issues when accessing certain files.

Another thing to note is that I’ve updated the project with new tags such as “game-server,” “gateway-server,” and “master-server.” These changes are meant to improve how the servers are managed and allowing multiple game and gateway servers in the future.

To avoid issues with zipping and unzipping the project, I recommend using git for version control. This way, only the modified files will be updated, and it should prevent any problems with file imports.

**Comment by WithinAmnesia** [comment]
https://github.com/SlayHorizon/godot-tiny-mmo-demo/issues/34#issuecomment-2428582770

I downloaded from this github page the project as if I were a regular user and I unzip and use its own separate director every time in the last decade or so. I have done this compartmentalized build archive / library as a way to test with a fresh install every time there is a new change to the engine and I have found the time to do so. I keep on hard-drive back ups of every test and compartmentalize each build separate from each other in case of needing to go back and restart building if an unforeseen issue happens with a build.

I have tested with administrator on Godot and the import issue persisted. I deleted the Godot folder then on this test directory and let the import process happen. The files still had import issues as before. I feel there is an issue where I solved this in the past yet have forgotten what I did exactly.

Windows has issue with this yet all previous builds are reading fine and have no import issues. This is odd. The issue error states try running the files in an editor once before and I feel I had this issue when i tried to copy paste a project directory last year.

I am guessing it reads fine on your original project or pc but I'm wondering if you have this issue I had before with the file imports failing to load after copying and pasting the project. I cannot confirm this but I can't rule it out either, it feels odd in the same ways as I had before with this copy paste project not reading import files things before in other Godot demos.

I remember looking up this errors looking for solutions on reddit and threads online and I fixed this same kind of issue before I think? Yet I've forgotten what the fixes were. This is not ideal but it happens with so much testing / things to remember I suppose.

"Another thing to note is that I’ve updated the project with new tags such as “game-server,” “gateway-server,” and “master-server.” These changes are meant to improve how the servers are managed and allowing multiple game and gateway servers in the future."
I cannot accurately comment on this for I feel the tests are not starting due to not all files reading and there fore any tests I do now are invalid for I simply do not have an accurate test with everything the way it should be. I want to say something about the new tags to be curious about possible changes or bugs for miss-matching but I read that the errors are saying the imported files are not reading. So its like trying to start a car with no fuel / battery left it's literally a non starter.😆 

"To avoid issues with zipping and unzipping the project, I recommend using git for version control. This way, only the modified files will be updated, and it should prevent any problems with file imports."
I don't think zipping is an issue for thats what most people will use and every other build up to this point worked fine with the zipped files from previous builds from Code Download ZIP on the main page. This is a mystery. I'll look up those solutions I forgot and hope there's something I can try.

I really would prefer this to be on my end and avoid a going back to a previous build and rebuilding to avoid a strange bug. I've had to do that before and lost lots of work so it's another reason I keep clean archived versions of each build just in case. Also it helps iterative design to try new things and if they work great, if not just keep trying with a duplicated build of the last working version, and try again until its stable and working more or less in a better state than before. Iterative building and fortified back ups and archived previous works helped myself from websites deleting my previous works or making them not able to share etc. I like Github buts its wed by microsoft https://en.wikipedia.org/wiki/GitHub#Acquisition_by_Microsoft and its one policy change from removing content. So I archive all the versions I test just in case; and it's already helped myself keep work alive as the internet changed throughout the decades.

Also I should bring up the Linux vs windows potential issues but my gut says it's not related and its a problem I solved before from a solution sourced from reddit / online Godot help threads. I'm really looking forward to trying out the new tags such as “game-server,” “gateway-server,” and “master-server.” I want to try and get a proper set up when I can for testing for quality and try to make things best ready for the community to tinker with across many set ups. I'll be tinkering and trying to find a solution to the import error. This is great that you are expanding and trying to make the servers really decent and future proofing. I think it's super cool! 😃 👍 ✨

**Comment by SlayHorizon** [comment]
Just tried the project from the downloaded zip and it's working fine on my side. Be sure to run Godot as an administrator.
Next version of Godot should fix the possible import issues but I'am waiting it to be in a stable state before moving the project to it.

**Comment by WithinAmnesia** [comment]
https://github.com/SlayHorizon/godot-tiny-mmo-demo/issues/34#issuecomment-2429136378

Yeah I think that's a good idea also with waiting for 4.4 stable release. Even the Redot community who needs a launch soon is waiting for 4.4 stable to release to make sure everything works well.

I'm looking around on reddit / Godot help threads with this import issue. It happens to windows 10 it seems, it's due to either file system permissions not being amazing or some kind of Godot missing files or not reading them right and giving errors. I remember typing in the error codes looking for matches before. I'll keep looking.

I'll look for a solution then share it once it's found and tested to work.

**Comment by WithinAmnesia** [comment]
Progress on testing / trying bug fixes:
<details>
![image](https://github.com/user-attachments/assets/bd383947-0efc-4d05-80da-d2b62f5073a9)
![image](https://github.com/user-attachments/assets/0573c7ca-f2fb-4744-9a92-b7b14eb92cb9)
</details>
I'm going to try disabling the safe save feature. It is recommended in the error messages. I'll try the previous methods of bug fixing with safe save off on the windows pc and see how that goes. 

https://github.com/godotengine/godot/issues/16274
Also I remember with a bigger file size project needing to wait a few minutes before running the project for the first time to let Godot read all the files before running. Or not running the project right away after a new copy and paste directory project duplication. I'll keep searching.

**Comment by WithinAmnesia** [comment]
Progress updates on bug fix testing.
<details>
I've disabled the safe save, closed godot 4.3-stable mono, made a new fresh directory, then imported the main page download file zip from unzipping Tiny MMO Demo zip in the new fresh directory, re-started godot 4.3-stable mono, imported the fresh directory, ran the fresh Tiny MMO Demo. This is the screen so far:
![image](https://github.com/user-attachments/assets/2fcaa082-dcfd-4516-9c61-4799bb757948)
I'll post more as things develop.
</details>

**Comment by WithinAmnesia** [comment]
Trying a new fresh project:

<details>
![image](https://github.com/user-attachments/assets/a292a934-9134-4fc1-b958-fef0e87e4459)
![image](https://github.com/user-attachments/assets/e21bda2d-1a86-4645-ba9a-55386efc1010)
My self deleting the paste failed project iteration of bug testing to start fresh.
![image](https://github.com/user-attachments/assets/b968c091-ccff-4df6-aad3-9dee2aa52af6)
![image](https://github.com/user-attachments/assets/8d7300cf-0d6c-4d50-9d3e-1ccd8f5dbda3)
![image](https://github.com/user-attachments/assets/e5f27d90-4780-4ca6-94e8-ed529480760a)
![image](https://github.com/user-attachments/assets/0977bb77-318c-4fe8-8791-5c824e817296)
![image](https://github.com/user-attachments/assets/e0228f40-9c14-4e5f-adaf-b4c7784490bb)
![image](https://github.com/user-attachments/assets/12aca787-d45e-4f26-bf2e-562de1f6fc78)
Making a fresh directory.
![image](https://github.com/user-attachments/assets/da7cd0f8-eef4-4772-b36b-5317b2efa549)
Finding the fresh zip file of the latest build.
![image](https://github.com/user-attachments/assets/31d76461-97f0-43b6-bfd9-410e3f37adbe)
Copying the zip file (that project above the zip file has never been run to keep it clean for archiving).
![image](https://github.com/user-attachments/assets/72ddfd19-b859-4850-9b9e-a8c80c3abed5)
Pasting the zip file into the fresh bug testing directory.
![image](https://github.com/user-attachments/assets/6db1d828-6198-4e1a-a132-ea898f75ee6e)
Extracting / unzipping the project zip file into the fresh directory.
![image](https://github.com/user-attachments/assets/eb8983bd-2c44-46c1-8d2c-1994d3aaf4eb)
![image](https://github.com/user-attachments/assets/98ab088d-743e-4325-b46d-c8d19421d880)
Here is the fresh extracted project that has never been run.
![image](https://github.com/user-attachments/assets/abbee0f0-47e8-4dd6-a37d-fb7b3b366950)
Myself closing Godot 4.3-stable mono.
(Myself trying to screenshot starting up godot again but the screenshot was 10 mb too big for github)
![image](https://github.com/user-attachments/assets/eb68dcbc-d5c4-4f8e-b9f6-acc99a788c25)
Godot 4.3-stable mono before importing the fresh project for bug testing.
![image](https://github.com/user-attachments/assets/f13f4bc7-3bb6-446e-87b1-30e22247948d)
Myself importing the fresh bug test project directory with fresh project unzip into Godot.
![image](https://github.com/user-attachments/assets/869a9cc8-13c9-4132-b1d7-a52bd9424dcf)
![image](https://github.com/user-attachments/assets/1d93ba03-7884-4ecc-9b4e-058b373891ff)
The project file path is valid.
![image](https://github.com/user-attachments/assets/02cb4346-c828-4d8d-98cf-ac1197eca78c)
Godot loading as the project starts up.
![image](https://github.com/user-attachments/assets/19b6a021-3d1d-4b53-9114-7091099b383d)
The output so far. I don't see any error messages.
![image](https://github.com/user-attachments/assets/31f95972-3549-4d47-a1e6-f15f06eddcd9)
![image](https://github.com/user-attachments/assets/fd76c85b-428c-41b1-ac29-002ce3765a67)
This looks stable. This is odd. I wonder if its due to the server instances not saving properly?


</details>

**Comment by WithinAmnesia** [comment]
https://github.com/SlayHorizon/godot-tiny-mmo-demo/issues/34#issuecomment-2430454822 The errors might be due to the text system not saving properly in Godot on my end somehow due to the text file error happening when I attempt to change the run instances to be like the read me:
![image](https://github.com/user-attachments/assets/edc88e8c-be00-49db-9480-2240b59d70ad)
I'll make a copy of this working bugtest and try changing the game title to see if its saving that busted or just the run instance part to further isolate the error.

**Comment by WithinAmnesia** [comment]
https://github.com/SlayHorizon/godot-tiny-mmo-demo/issues/34#issuecomment-2430459900
Myself starting to make a fresh bug test copy directory for clean bug testing to test the saving.
<details>

![image](https://github.com/user-attachments/assets/c9533fcc-7356-45ea-bb5e-24b581d3b62c)
![image](https://github.com/user-attachments/assets/cd2cbfea-a282-4d9c-9654-8b495c5477f4)
The previous bug test fresh project directory (no changes or no new saves with no errors)

</details>

**Comment by WithinAmnesia** [comment]
Trying my hypothesis / hunch / idea of The import issue looks to be isolated to changing the run instance settings:

<details>

I will recreate the 'Bugtest 002' changed title but as 'Bugtest 003' to keep iteration names and moreover so as to not introduce any copy past errors and make this as clean as possible.
![image](https://github.com/user-attachments/assets/4eb6bc19-64ce-45ee-9c0b-e2a1a2aa81d6)
![image](https://github.com/user-attachments/assets/c27cedbf-f6df-4efa-9f3b-8a8d5a64ee2e)
Here is a fresh unzipped latest build project.
![image](https://github.com/user-attachments/assets/b168ff45-9564-4f3b-af5f-f9c139363b25)
It has no been run yet since it is freshly extracted /unzipped from the zip file.
![image](https://github.com/user-attachments/assets/a6be427f-7408-4f36-9bbd-7117dc35fbc2)
Importing the project file of bug test 003.
![image](https://github.com/user-attachments/assets/feb4eca1-f131-4cec-929f-493a79aed48a)
A valid path again.
![image](https://github.com/user-attachments/assets/52522878-df5c-40b6-b62a-1bdc75fbb08b)
no errors so far.
![image](https://github.com/user-attachments/assets/b11cc085-a8aa-477a-b28a-ca5f56c8242f)
Project name change.
![image](https://github.com/user-attachments/assets/f57aff1a-137e-4141-8e20-e011ac449b71)
Project runs without errors so far.
![image](https://github.com/user-attachments/assets/b2af5df7-3153-4b57-95b6-70b00829f3eb)
Project run closed and has no errors so far.
![image](https://github.com/user-attachments/assets/00681092-c95c-4f40-9507-c2db8b3dcc86)
Double checking safe save is off.
![image](https://github.com/user-attachments/assets/17ce612f-5ade-4117-9af5-03535d9b4f21)
I will try step by step to make small changes until a bug is encountered with the run instances to try and isolate the bug / issues
![image](https://github.com/user-attachments/assets/c895ee79-756d-444b-92a7-33d4be061b5d)
I clicked run multiple instances. I will run this to see if it works.
![image](https://github.com/user-attachments/assets/f58931f9-4491-4583-b545-10aa160b4774)
So far so good.
![image](https://github.com/user-attachments/assets/6d94c0dc-5c95-4248-99f9-9a5b7aeaed33)
The debugger turned on and I'll show the results. Hmmm odd I didn't notice this before. Perhaps the debugger turns on at least after the run instances are changed? I'll watch this too.
![image](https://github.com/user-attachments/assets/fba55505-35aa-4ceb-a210-963338e67a89)
![image](https://github.com/user-attachments/assets/ff12b292-11df-48af-90dc-6b193e424da5)
![image](https://github.com/user-attachments/assets/86288bd4-db6d-46c3-b03c-c9ee3164ad1e)
![image](https://github.com/user-attachments/assets/95bb168e-2993-4656-837a-5a135f94c9cc)
![image](https://github.com/user-attachments/assets/faf85396-b0e2-45b2-b36e-93fa097f1699)
![image](https://github.com/user-attachments/assets/30d52468-121e-4b0c-914e-21ab21ad2519)
![image](https://github.com/user-attachments/assets/919c70f0-0235-451c-b42c-013896a1ee1a)
It looks ok in the debugger.
![image](https://github.com/user-attachments/assets/fe1c6566-ab82-40ed-9c9e-18db37233fd7)
Again the output has no errors but it shows the debugger turned on after the run instances as changed.
![image](https://github.com/user-attachments/assets/e82a2595-a19f-4a69-9ad4-8589c4edb175)
For test purposes I will step by step gradually recreate the default readme run instances to keep things clean and focused to try and isolate the bug the best as possible.
![image](https://github.com/user-attachments/assets/04616ac6-4a1f-4fe0-8ccd-c2a48a385de8)
1 run instance changed to run 4 instances. I'll run the project and see if that works.
![image](https://github.com/user-attachments/assets/44509a7f-6497-4898-848c-6957ea8e3c79)
No bugs so far.
![image](https://github.com/user-attachments/assets/eb998805-d365-4025-8558-2d2823f191a1)
No bugs running 4 instances so far.
![image](https://github.com/user-attachments/assets/ec23d5ad-abf1-42a9-bf1c-aa5aee894222)
Closed the thing.
![image](https://github.com/user-attachments/assets/6aa88b57-5ebe-4c43-8708-7e519901c37a)
I checked each of these 4 debugger sessions are they are the same minus 4 of them being there now. It gets screenshot heavy if I do ~16 screen shots of each tab of the same thing. I'll show any differences or things of note.
![image](https://github.com/user-attachments/assets/7ee3b845-3817-4a04-8119-02bb643e560e)
I'll write this as "--headless" and run and test and report any changes.
![image](https://github.com/user-attachments/assets/7b74aa47-7876-4fff-9a15-acd271f2feff)
![image](https://github.com/user-attachments/assets/93106169-f0c2-4058-afb2-ba63064e7dc2)
![image](https://github.com/user-attachments/assets/c16ac1d9-bf59-43d7-96a1-201d5b8bf980)
No issues. I'll try doing the second instance as "--headless".
![image](https://github.com/user-attachments/assets/3221ad3d-44cb-405e-9d84-8957038e9605)
![image](https://github.com/user-attachments/assets/e3e1830b-fd0a-453a-a320-8b8751b74416)
![image](https://github.com/user-attachments/assets/d2271bf4-45ca-4ad1-a5f9-d4345e764cc1)
![image](https://github.com/user-attachments/assets/175ea456-0963-46d2-a073-056c742b39f1)
No issues again.
I'll change this to match the readme file and put "gateway_server"
![image](https://github.com/user-attachments/assets/2970cfff-0023-48d5-a6d5-26ae27795b32)
![image](https://github.com/user-attachments/assets/6231b543-148c-4ecf-8e94-b906ac9f5aff)
I'll trying running this to see if anything happens.
![image](https://github.com/user-attachments/assets/e781988f-adbb-498d-aaed-3c791de24df3)
![image](https://github.com/user-attachments/assets/3547e2ad-5534-44f0-baf0-6716573c3bbb)
![image](https://github.com/user-attachments/assets/56ed7a2d-b28a-4a45-9f82-0cf9df2504a4)
I checked all the tabs of the debugger for all 4 sessions and nothing changed / is odd / it looks usual.
![image](https://github.com/user-attachments/assets/8408df1f-2887-4ff1-8cf1-b1bc7c99da16)
I'll try to add in "game_server" and run the project and see how that goes.
![image](https://github.com/user-attachments/assets/8b6e4370-684c-4434-9492-5b117147c451)
![image](https://github.com/user-attachments/assets/5c21f333-b82a-45ef-a886-6a3ebb050370)
So far so good.
![image](https://github.com/user-attachments/assets/e2b440fd-a48b-47ac-bb9d-7738c3babf3d)
![image](https://github.com/user-attachments/assets/16884c83-95c9-42ec-b97b-178b3bc83df3)
![image](https://github.com/user-attachments/assets/1536cf72-6636-4aad-a2ae-32aea483e854)
It looks okay so far with nothing to note out of the ordinary.
![image](https://github.com/user-attachments/assets/16ee3884-3101-4508-b92c-99b1dc99d7ae)
Testing client run instance.
![image](https://github.com/user-attachments/assets/01668f2e-8de5-4ed8-a5a4-7f7c6feec425)
![image](https://github.com/user-attachments/assets/e509ec23-f814-4d27-aafc-0ad935de7646)
Errors happening with the client. 'Failed to connect to server' Stopping the test run and checking for errors.
![image](https://github.com/user-attachments/assets/d0ec3ce6-95a9-4aee-8ee3-3061f9a1a57e)
I checked the debugger tabs, nothing odd.
![image](https://github.com/user-attachments/assets/b299812e-6857-4fe0-89d9-e9a0700ab59a)
No errors. I'll run it again and try to get the client to appear for testing.
![image](https://github.com/user-attachments/assets/5698b74a-d2aa-4430-b3d9-8c6fbe3a7164)
![image](https://github.com/user-attachments/assets/227be6ba-eabb-433b-8803-4e926c12e34e)
The client is appearing. There are no bug error messages but the server is failing to connect. I will stop the test run and duplicate 1 for 1 the default debug screen run multiple instances set up and test that.
![image](https://github.com/user-attachments/assets/a8d02563-720d-43eb-8474-25084b7b7288)
![image](https://github.com/user-attachments/assets/b7e42e90-96d3-4755-8324-a78e35840afc)
I checked the debugger tabs and nothing out of the ordinary.
![image](https://github.com/user-attachments/assets/ba56e5e2-7a49-46b1-b7c7-976088f8a701)
This looks to be a match of the readme default run instance set up.
![image](https://github.com/user-attachments/assets/b7cdb396-00e4-4280-9864-09657ae7762a)
As noted to double check both of them together.
![image](https://github.com/user-attachments/assets/75acbbce-3e25-4ba6-b6ca-7bf14be273ca)
I will run the project to test for bugs with windows 10 Godot 4.3-stable mono with safe save off and and exact match to the default readme run instance setup.
![image](https://github.com/user-attachments/assets/56e24305-1224-47d6-9629-1c8333e7929d)
Triple checking the safe save is off. The safe save is off.
![image](https://github.com/user-attachments/assets/ae1c0bae-1eea-4e2b-82f0-c64bb4c99e67)
![image](https://github.com/user-attachments/assets/b9475c92-a3ae-421c-99e4-2b15fe81ec04)
Failed to connect to server from both clients. Yet no errors so far when running.
![image](https://github.com/user-attachments/assets/1a0ccd3d-97d2-4b7b-b8ad-9cd9af7fc1d2)
Stopped the running of the bug test.
![image](https://github.com/user-attachments/assets/fa6a33eb-87a7-45da-9dbc-a8680cadf6c5)
The debugger tabs look regular. I do not see any error messages.

I should run a test where I add up to 16 clients and see if errors happen. I should report these findings and the connection failed on the default run instance setup though first.

</details>

@SlayHorizon I found a failed to connect error with the default set up with a windows 10 on a fresh directory and fresh unzipped github zip file with safe save turned off. There are no error messages about import issues with this set up but the game does not connect.

I am not sure if this is known or intended with this step. I am still iteratively trying to isolate the error I found but I figured to bring this up in case it is a new but of the clients not connecting with no error messages. thank you for working on all of this and it is really cool.

I think I'm close to isolating the original bug but saving works and it looks like either a safe save windows 10 thing or a Godot engine issue but I'll keep crawling forward with the iterative bug testing. What do you think of this so far? Is it supposed to connect by default like as before or are we in an in-between set as things are being connected together better later? This is really awesome and I look forward to helping more too. 😄 🤔 👍 ✨ 💯 🚀

**Comment by WithinAmnesia** [comment]
Here I am trying a shorter directory and project title (maybe it was a case of too long of file path?)
![image](https://github.com/user-attachments/assets/dd7bcc79-2170-483e-9ccd-dc2dd6cccf5e)
![image](https://github.com/user-attachments/assets/8ad2602f-46f2-4c34-8a44-90e56ce6a947)
It works!
![image](https://github.com/user-attachments/assets/4aec6663-5e36-4a27-b9ae-c05b26999be5)
![image](https://github.com/user-attachments/assets/92426822-ca2d-4162-ad08-f0276dba2159)
It works with safe save on as well.

Error hypothesis: Too long of directory name and title name leads to windows 10 not being able to read files. The new build might have has built in longer paths and my testing setup broke due it being super close to running out of amount of characters / letters / numbers to keep working / saving / writing properly. I think my error tests worked due to smaller names and directory paths.

@SlayHorizon Your work has no bugs and thankfully it was on my end and it had to do with I think too long file path names that got in the way of windows 10 saving / reading and writing properly.

New info, recommend shorter project directory path (and or if needed shorter project titles also) on Windows 10 if read / write / unable to read file errors happen. Safe save works fine. This is great! The new game features are super cool. I like the xp and game game modes and regular no rules and hardcore. It reminds me of OSRS and Path of Exile and Turtle WoW and Classic WoW. Great job too!
💪 😃 👍 🎆 🎇 🌟 ✨ 🥇 💯 🏰 🐉 ⚔️ ⛰️ 🗺️ 🚀

**Comment by SlayHorizon** [comment]
Glad it's working now.
The random username generator is really primitive and mainly useful for test purpose, may consider using a better one for more serious game.

It's ok I will consider changing the project name on Godot to only "Tiny-MMO" and also on Github by simply calling it "godot-tiny-mmo".
